#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 2: FASTA Parsing and Sample Analysis Script
Parse FASTA files generated by LigandMPNN and extract sequences and
confidence metrics.
"""

import argparse
import math
import re
from collections import Counter
from pathlib import Path

import pandas as pd

# 20 standard amino acids
AA20 = list("ACDEFGHIKLMNPQRSTVWY")


# ============== FASTA Parsing ==============
HDR_RE = re.compile(
    r"^>(?P<name>[^,]+), id=(?P<id>\d+), T=(?P<T>[-0-9.eE+-]+), seed=(?P<seed>\d+), "
    r"overall_confidence=(?P<overall>[0-9.eE+-]+), ligand_confidence=(?P<ligand>[0-9.eE+-]+), "
    r"seq_rec=(?P<seq_rec>[0-9.eE+-]+)$"
)


def read_fasta(path: Path):
    """Read a FASTA file."""
    records = []
    header = None
    seq_chunks = []

    with path.open() as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            if line.startswith(">"):
                if header is not None:
                    records.append((header, "".join(seq_chunks)))

                header = line
                seq_chunks = []
            else:
                seq_chunks.append(line)

    if header is not None:
        records.append((header, "".join(seq_chunks)))

    return records


def pick_designed_segment(full_seq: str, segment_index: int) -> str:
    """Extract the designed chain segment from the full sequence."""
    parts = full_seq.split(":")
    return parts[segment_index] if len(parts) > 1 else full_seq


def parse_comma_separated(s: str):
    """Parse a comma-separated string."""
    return [x.strip() for x in s.split(",") if x.strip()]


# ============== Main Function ==============
def main():
    ap = argparse.ArgumentParser(
        description=(
            "Parse LigandMPNN FASTA results and generate sample statistics, "
            "unique-sequence statistics, and position-frequency analysis."
        )
    )

    # Input and output
    ap.add_argument(
        "--mpnn_out_root",
        required=True,
        help="Root directory generated by Step 1 containing folders 6-16.",
    )
    ap.add_argument(
        "--outdir",
        default="analysis_T0p0001",
        help="Output directory for analysis results.",
    )

    # Ring-length configuration
    ap.add_argument(
        "--ring_lengths",
        default="6,7,8,9,10,11,12,13,14,15,16",
        help="Comma-separated ring-length list.",
    )

    # Seed configuration
    ap.add_argument(
        "--seeds",
        default="seed0,seed1,seed2",
        help="Comma-separated seed-directory list.",
    )

    # Design configuration
    ap.add_argument(
        "--segment_index",
        type=int,
        default=-1,
        help=(
            "Index of the designed chain after splitting the sequence by ':'. "
            "Use -1 for the last segment."
        ),
    )

    args = ap.parse_args()

    mpnn_root = Path(args.mpnn_out_root)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    ring_lengths = parse_comma_separated(args.ring_lengths)
    seed_names = parse_comma_separated(args.seeds)

    if not mpnn_root.is_dir():
        raise SystemExit(f"mpnn_out_root does not exist: {mpnn_root}")

    # ============== Collect All FASTA Files ==============
    fasta_files = []

    for ring_len in ring_lengths:
        for seed in seed_names:
            # Directory structure: mpnn_root / ring_length
            ring_dir = mpnn_root / ring_len

            if not ring_dir.is_dir():
                print(f"[WARN] Directory does not exist: {ring_dir}")
                continue

            # Iterate over each PDB subdirectory
            for pdb_dir in sorted(ring_dir.iterdir()):
                if not pdb_dir.is_dir():
                    continue

                # Enter the seqs directory under seedx
                seqs_dir = pdb_dir / seed / "seqs"

                if not seqs_dir.is_dir():
                    continue

                # Find FASTA files in the seqs directory
                found = sorted(seqs_dir.glob("*.fa"))
                fasta_files.extend(found)

    if not fasta_files:
        raise SystemExit(
            "No .fa files were found. Please check the paths.\n"
            f"mpnn_out_root = {mpnn_root}\n"
            f"ring_lengths = {ring_lengths}\n"
            f"seeds = {seed_names}"
        )

    print(f"\n{'=' * 60}")
    print(f"Found {len(fasta_files)} FASTA files to process")
    print(f"{'=' * 60}\n")

    # ============== Parse FASTA Files ==============
    rows = []

    for fa in fasta_files:
        # Directory structure:
        # mpnn_root / ring_length / pdb_name / seed_name / seqs / file.fa
        #
        # fa.parents[0] -> seqs
        # fa.parents[1] -> seed_name
        # fa.parents[2] -> pdb_name
        # fa.parents[3] -> ring_length
        ring_len = fa.parents[3].name
        pdb_name = fa.parents[2].name
        seed_folder = fa.parents[1].name

        records = read_fasta(fa)
        native_designed_seq = None

        for header, full_seq in records:
            designed_seq = pick_designed_segment(
                full_seq,
                args.segment_index,
            )

            # The first record is usually the native/reference sequence
            if ", id=" not in header:
                native_designed_seq = designed_seq
                continue

            m = HDR_RE.match(header)

            if not m:
                print(f"[WARN] Header parsing failed: {header}")
                continue

            overall = float(m.group("overall"))
            ligand = float(m.group("ligand"))

            if overall <= 0 or ligand <= 0:
                print(
                    f"[WARN] Confidence is <= 0; skipping: "
                    f"{fa} | {header}"
                )
                continue

            rows.append(
                {
                    "ring_len": int(ring_len),
                    "scaffold_name": pdb_name,
                    "seed_folder": seed_folder,
                    "source_fa": str(fa),
                    "sample_id": int(m.group("id")),
                    "sample_seed": int(m.group("seed")),
                    "T": float(m.group("T")),
                    "overall_confidence": overall,
                    "ligand_confidence": ligand,
                    "nll_per_res": -math.log(overall),
                    "ligand_nll_per_res": -math.log(ligand),
                    "avg_log_prob": math.log(overall),
                    "seq_rec": float(m.group("seq_rec")),
                    "full_seq": full_seq,
                    "designed_seq": designed_seq,
                    "native_designed_seq": native_designed_seq,
                    "design_len": len(designed_seq),
                }
            )

    if not rows:
        raise SystemExit(
            "FASTA files were found, but no valid samples were parsed."
        )

    df = pd.DataFrame(rows)
    df = df.sort_values(
        [
            "ring_len",
            "scaffold_name",
            "seed_folder",
            "sample_id",
        ]
    ).reset_index(drop=True)

    # ============== Sequence-Length Consistency Check ==============
    length_check = (
        df.groupby(
            ["ring_len", "scaffold_name"]
        )["design_len"].nunique()
    )

    bad = length_check[length_check > 1]

    if not bad.empty:
        msg = [
            "The designed_seq lengths are inconsistent for the following "
            "(ring_len, scaffold_name) groups:"
        ]

        for idx, value in bad.items():
            msg.append(f"{idx}: {value} different lengths")

        raise ValueError("\n".join(msg))

    # ============== Output 1: All Samples ==============
    df.to_csv(
        outdir / "all_samples.csv",
        index=False,
    )
    print(
        f"Wrote: {outdir / 'all_samples.csv'} "
        f"({len(df)} samples)"
    )

    # ============== Output 2: Unique-Sequence Statistics ==============
    unique_df = (
        df.groupby(
            [
                "ring_len",
                "scaffold_name",
                "designed_seq",
            ],
            as_index=False,
        )
        .agg(
            count=("designed_seq", "size"),
            mean_nll=("nll_per_res", "mean"),
            min_nll=("nll_per_res", "min"),
            max_conf=("overall_confidence", "max"),
            mean_seq_rec=("seq_rec", "mean"),
            native_designed_seq=("native_designed_seq", "first"),
        )
        .sort_values(
            [
                "ring_len",
                "scaffold_name",
                "count",
                "mean_nll",
            ],
            ascending=[True, True, False, True],
        )
        .reset_index(drop=True)
    )

    unique_df.to_csv(
        outdir / "unique_sequences.csv",
        index=False,
    )
    print(
        f"Wrote: {outdir / 'unique_sequences.csv'} "
        f"({len(unique_df)} unique sequences)"
    )

    # ============== Output 3: Position-Frequency Analysis ==============
    pos_rows = []

    for (ring_len, scaffold_name), sub in df.groupby(
        ["ring_len", "scaffold_name"]
    ):
        seqs = sub["designed_seq"].tolist()
        K = len(seqs)

        if K == 0:
            continue

        L = len(seqs[0])

        for pos in range(L):
            counts = Counter(sequence[pos] for sequence in seqs)
            probs = {
                aa: counts.get(aa, 0) / K
                for aa in AA20
            }

            entropy = -sum(
                probability * math.log(probability)
                for probability in probs.values()
                if probability > 0
            )

            top_aa, top_count = counts.most_common(1)[0]

            for aa in AA20:
                pos_rows.append(
                    {
                        "ring_len": ring_len,
                        "scaffold_name": scaffold_name,
                        "position_1based": pos + 1,
                        "aa": aa,
                        "count": counts.get(aa, 0),
                        "freq": probs[aa],
                        "top_aa": top_aa,
                        "top_freq": top_count / K,
                        "entropy_nats": entropy,
                        "K": K,
                    }
                )

    pos_df = pd.DataFrame(pos_rows)
    pos_df.to_csv(
        outdir / "position_frequencies.csv",
        index=False,
    )
    print(
        f"Wrote: {outdir / 'position_frequencies.csv'} "
        f"({len(pos_df)} position records)"
    )

    # ============== Summary Statistics ==============
    print(f"\n{'=' * 60}")
    print("Analysis Summary")
    print(f"{'=' * 60}")
    print(f"Total samples: {len(df)}")
    print(f"Unique sequences: {len(unique_df)}")
    print(f"Ring lengths: {sorted(df['ring_len'].unique())}")
    print(f"Scaffolds: {df['scaffold_name'].nunique()}")
    print(f"Output directory: {outdir.resolve()}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()